apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-danae
  labels:
    app: mi-app-danae
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app-danae
  template:
    metadata:
      labels:
        app: mi-app-danae
    spec:
      containers:
        - name: mi-app-danae
          image: mi-app-danae:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "v1"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
