apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mi-app-danae.fullname" . }}
  labels:
    {{- include "mi-app-danae.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mi-app-danae.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mi-app-danae.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
