apiVersion: v1
kind: Service
metadata:
  name: {{ include "mi-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mi-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
